// Comprehensive Google Keyboard (Gboard) Emoji Dataset with Categories and Search Keywords

export const GBOARD_EMOJI_CATEGORIES = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😊',
    emojis: [
      { char: '😀', name: 'grinning face happy smile' },
      { char: '😃', name: 'grinning face big eyes happy' },
      { char: '😄', name: 'grinning face smiling eyes laugh' },
      { char: '😁', name: 'beaming face smiling eyes grin' },
      { char: '😆', name: 'grinning squinting face laugh haha' },
      { char: '😅', name: 'grinning face sweat relief phew' },
      { char: '🤣', name: 'rolling on floor laughing rofl' },
      { char: '😂', name: 'face with tears of joy laugh lol' },
      { char: '🙂', name: 'slightly smiling face smile' },
      { char: '🙃', name: 'upside down face silly sarcasm' },
      { char: '😉', name: 'winking face wink flirt' },
      { char: '😊', name: 'smiling face smiling eyes warm' },
      { char: '😇', name: 'smiling face halo angel innocent' },
      { char: '🥰', name: 'smiling face hearts love adore' },
      { char: '😍', name: 'heart eyes love enamored' },
      { char: '🤩', name: 'star struck excited amazed' },
      { char: '😘', name: 'face blowing kiss love' },
      { char: '😗', name: 'kissing face kiss' },
      { char: '😚', name: 'kissing face closed eyes' },
      { char: '😙', name: 'kissing face smiling eyes' },
      { char: '😋', name: 'face savoring food delicious yum' },
      { char: '😛', name: 'face with tongue playful silly' },
      { char: '😜', name: 'winking face tongue silly crazy' },
      { char: '🤪', name: 'zany face wild crazy goofy' },
      { char: '😝', name: 'squinting face tongue playful' },
      { char: '🤑', name: 'money mouth face rich cash' },
      { char: '🤗', name: 'smiling face open hands hug warm' },
      { char: '🤭', name: 'face hand over mouth oops giggle' },
      { char: '🤫', name: 'shushing face quiet secret shh' },
      { char: '🤔', name: 'thinking face hmm wonder ponder' },
      { char: '🫡', name: 'saluting face salute respect yes sir' },
      { char: '🤐', name: 'zipper mouth silent secret' },
      { char: '🤨', name: 'face raised eyebrow skeptical suspect' },
      { char: '😐', name: 'neutral face straight poker' },
      { char: '😑', name: 'expressionless face blank' },
      { char: '😶', name: 'face without mouth quiet silent' },
      { char: '😏', name: 'smirking face smug smirk flirty' },
      { char: '😒', name: 'unamused face bored annoyed' },
      { char: '🙄', name: 'face rolling eyes sarcasm whatever' },
      { char: '😬', name: 'grimacing face awkward oops nervous' },
      { char: '🤥', name: 'lying face pinocchio liar' },
      { char: '😌', name: 'relieved face calm peaceful' },
      { char: '😔', name: 'pensive face sad regret' },
      { char: '😪', name: 'sleepy face tired sleep' },
      { char: '🤤', name: 'drooling face drool crave' },
      { char: '😴', name: 'sleeping face zzz snore' },
      { char: '😷', name: 'face medical mask sick virus' },
      { char: '🤒', name: 'face thermometer sick fever' },
      { char: '🤕', name: 'face head bandage hurt injury' },
      { char: '🤢', name: 'nauseated face gross vomit green' },
      { char: '🤮', name: 'face vomiting puke sick barf' },
      { char: '🤧', name: 'sneezing face sneeze cold allergy' },
      { char: '🥵', name: 'hot face sweating heat red' },
      { char: '🥶', name: 'cold face freezing ice blue' },
      { char: '🥴', name: 'woozy face dizzy drunk tipsy' },
      { char: '😵', name: 'dizzy face knocked out shocked' },
      { char: '🤯', name: 'exploding head mind blown shock wow' },
      { char: '🤠', name: 'cowboy hat face yeehaw western' },
      { char: '🥳', name: 'partying face party celebrate hat horn' },
      { char: '🥸', name: 'disguised face disguise glasses mustache' },
      { char: '😎', name: 'smiling face sunglasses cool chill' },
      { char: '🤓', name: 'nerd face geek smart glasses' },
      { char: '🧐', name: 'face monocle classy inspect smart' },
      { char: '😕', name: 'confused face unsure puzzled' },
      { char: '😟', name: 'worried face anxious concerned' },
      { char: '🙁', name: 'slightly frowning face sad' },
      { char: '😮', name: 'face open mouth surprise wow' },
      { char: '😯', name: 'hushed face surprised gasping' },
      { char: '😲', name: 'astonished face shocked amazed' },
      { char: '😳', name: 'flushed face embarrassed blush wide eyes' },
      { char: '🥺', name: 'pleading face puppy eyes please beg' },
      { char: '😦', name: 'frowning face open mouth' },
      { char: '😧', name: 'anguished face stressed' },
      { char: '😨', name: 'fearful face scared afraid' },
      { char: '😰', name: 'anxious face sweat nervous stress' },
      { char: '😥', name: 'sad relieved face sweat phew' },
      { char: '😢', name: 'crying face tear sad' },
      { char: '😭', name: 'loudly crying face sob weep tears' },
      { char: '😱', name: 'face screaming fear scream panic' },
      { char: '😖', name: 'confounded face frustrated' },
      { char: '😣', name: 'persevering face struggle endure' },
      { char: '😞', name: 'disappointed face sad down' },
      { char: '😓', name: 'downcast face sweat tired' },
      { char: '😩', name: 'weary face tired exhausted' },
      { char: '😫', name: 'tired face stress whine' },
      { char: '🥱', name: 'yawning face yawn sleepy bored' },
      { char: '😤', name: 'face steam nose proud triumph angry' },
      { char: '😡', name: 'pouting face mad rage red' },
      { char: '😠', name: 'angry face mad furious' },
      { char: '🤬', name: 'face symbols mouth cursing swear' },
      { char: '😈', name: 'smiling face horns devil evil mischief' },
      { char: '👿', name: 'angry face horns devil mad' },
      { char: '💀', name: 'skull dead skeleton laugh died' },
      { char: '☠️', name: 'skull crossbones danger poison' },
      { char: '💩', name: 'pile poo poop funny brown' },
      { char: '🤡', name: 'clown face circus foolish' },
      { char: '👹', name: 'ogre monster japanese demon' },
      { char: '👺', name: 'goblin mask tengu red' },
      { char: '👻', name: 'ghost spooky halloween boo' },
      { char: '👽', name: 'alien ufo extra terrestrial' },
      { char: '👾', name: 'alien monster retro space invader game' },
      { char: '🤖', name: 'robot bot AI automated machine' }
    ]
  },
  {
    id: 'people',
    name: 'People & Body',
    icon: '🧑',
    emojis: [
      { char: '👋', name: 'waving hand wave hello goodbye hi' },
      { char: '🤚', name: 'raised back of hand stop' },
      { char: '🖐️', name: 'hand splayed five fingers stop' },
      { char: '✋', name: 'raised hand high five stop' },
      { char: '🖖', name: 'vulcan salute spock star trek peace' },
      { char: '🫱', name: 'rightwards hand reach' },
      { char: '🫲', name: 'leftwards hand reach' },
      { char: '🫳', name: 'palm down hand drop drop the mic' },
      { char: '🫴', name: 'palm up hand offer catch' },
      { char: '👌', name: 'ok hand perfect nice good' },
      { char: '🤌', name: 'pinched fingers italian what do you want' },
      { char: '🤏', name: 'pinching hand tiny little bit small' },
      { char: '✌️', name: 'victory hand peace two v' },
      { char: '🤞', name: 'crossed fingers luck hope wish' },
      { char: '🫰', name: 'hand with index thumb crossed korean finger heart love' },
      { char: '🤟', name: 'love you gesture sign language' },
      { char: '🤘', name: 'sign of horns rock on metal concert' },
      { char: '🤙', name: 'call me hand phone shaka hang loose' },
      { char: '👈', name: 'backhand index pointing left point' },
      { char: '👉', name: 'backhand index pointing right point' },
      { char: '👆', name: 'backhand index pointing up point' },
      { char: '🖕', name: 'middle finger rude swear' },
      { char: '👇', name: 'backhand index pointing down point' },
      { char: '☝️', name: 'index pointing up point number one' },
      { char: '🫵', name: 'index pointing at viewer you' },
      { char: '👍', name: 'thumbs up approve yes like good great ok agree' },
      { char: '👎', name: 'thumbs down disapprove no dislike bad' },
      { char: '✊', name: 'raised fist power strength solidarity' },
      { char: '👊', name: 'oncoming fist bump punch attack' },
      { char: '🤛', name: 'left facing fist bump' },
      { char: '🤜', name: 'right facing fist bump' },
      { char: '👏', name: 'clapping hands applause bravo congrats clap' },
      { char: '🙌', name: 'raising hands celebrate praise hooray' },
      { char: '🫶', name: 'heart hands love care support' },
      { char: '👐', name: 'open hands hug welcome' },
      { char: '🤲', name: 'palms up together pray prayer' },
      { char: '🤝', name: 'handshake deal agree partner collaboration trade' },
      { char: '🙏', name: 'folded hands pray please thanks gratitude namaste' },
      { char: '✍️', name: 'writing hand write pencil pen document notes' },
      { char: '💅', name: 'nail polish sassy slay fab manicure' },
      { char: '🤳', name: 'selfie camera photo picture' },
      { char: '💪', name: 'flexed biceps muscle strength strong gym power' },
      { char: '🦾', name: 'mechanical arm cyborg prosthetic bionic tech' },
      { char: '🦿', name: 'mechanical leg prosthetic bionic tech' },
      { char: '🦵', name: 'leg kick run' },
      { char: '🦶', name: 'foot step walk' },
      { char: '👂', name: 'ear listen hear sound' },
      { char: '🦻', name: 'ear with hearing aid accessibility hear' },
      { char: '👃', name: 'nose smell sniff' },
      { char: '🧠', name: 'brain smart think mind intelligence AI psychology' },
      { char: '🫀', name: 'anatomical heart biology organ pulse' },
      { char: '🫁', name: 'lungs breath breathing health' },
      { char: '🦷', name: 'tooth dentist dental teeth smile' },
      { char: '🦴', name: 'bone dog skeleton' },
      { char: '👀', name: 'eyes look see gaze look at this watch' },
      { char: '👁️', name: 'eye vision see' },
      { char: '👅', name: 'tongue lick taste silly' },
      { char: '👄', name: 'mouth lips kiss speak talk' },
      { char: '👶', name: 'baby infant young' },
      { char: '🧒', name: 'child kid youth' },
      { char: '👦', name: 'boy young male' },
      { char: '👧', name: 'girl young female' },
      { char: '🧑', name: 'person adult human' },
      { char: '👱', name: 'person blond hair' },
      { char: '👨', name: 'man male adult' },
      { char: '🧔', name: 'person beard bearded man' },
      { char: '👨‍🦰', name: 'man red hair' },
      { char: '👨‍🦱', name: 'man curly hair' },
      { char: '👨‍🦳', name: 'man white hair' },
      { char: '👨‍🦲', name: 'man bald' },
      { char: '👩', name: 'woman female adult' },
      { char: '👩‍🦰', name: 'woman red hair' },
      { char: '👩‍🦱', name: 'woman curly hair' },
      { char: '👩‍🦳', name: 'woman white hair' },
      { char: '👩‍🦲', name: 'woman bald' },
      { char: '🧓', name: 'older person elder senior' },
      { char: '👴', name: 'old man grandfather senior' },
      { char: '👵', name: 'old woman grandmother senior' },
      { char: '🧑‍💻', name: 'technologist coder developer engineer laptop programmer hacker' },
      { char: '👨‍💻', name: 'man technologist coder developer programmer engineer' },
      { char: '👩‍💻', name: 'woman technologist coder developer programmer engineer' },
      { char: '🧑‍🏫', name: 'teacher professor lecturer mentor tutor instructor' },
      { char: '🧑‍🎓', name: 'student graduate graduation study college campus degree' },
      { char: '🧑‍🔬', name: 'scientist lab researcher chemistry biology data physics' },
      { char: '🧑‍💼', name: 'office worker business manager lead professional' },
      { char: '🧑‍🚀', name: 'astronaut space nasa rocket cosmic' },
      { char: '🦸', name: 'superhero hero power save' },
      { char: '🦹', name: 'supervillain villain evil' }
    ]
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { char: '🐶', name: 'dog face puppy pet animal' },
      { char: '🐱', name: 'cat face kitten pet animal meow' },
      { char: '🐭', name: 'mouse face rodent' },
      { char: '🐹', name: 'hamster face pet rodent cute' },
      { char: '🐰', name: 'rabbit face bunny easter' },
      { char: '🦊', name: 'fox face sly clever' },
      { char: '🐻', name: 'bear face grizzly teddy' },
      { char: '🐼', name: 'panda face bear bamboo cute' },
      { char: '🐻‍❄️', name: 'polar bear arctic ice snow' },
      { char: '🐨', name: 'koala australia eucalyptus' },
      { char: '🐯', name: 'tiger face wild feline stripes' },
      { char: '🦁', name: 'lion face king king of jungle brave' },
      { char: '🐮', name: 'cow face moo milk cattle' },
      { char: '🐷', name: 'pig face oink pork' },
      { char: '🐸', name: 'frog face toad ribbit green' },
      { char: '🐵', name: 'monkey face ape animal primate' },
      { char: '🙈', name: 'see no evil monkey blind ignore' },
      { char: '🙉', name: 'hear no evil monkey deaf' },
      { char: '🙊', name: 'speak no evil monkey quiet secret' },
      { char: '🐒', name: 'monkey jungle climb' },
      { char: '🐔', name: 'chicken hen cluck poultry' },
      { char: '🐧', name: 'penguin antarctic bird ice cute' },
      { char: '🐦', name: 'bird tweet flying animal' },
      { char: '🐤', name: 'baby chick cute yellow' },
      { char: '🦆', name: 'duck quack bird lake' },
      { char: '🦅', name: 'eagle raptor bird predator fly america' },
      { char: '🦉', name: 'owl nocturnal wise wisdom bird smart' },
      { char: '🦇', name: 'bat vampire nocturnal cave spooky' },
      { char: '🐺', name: 'wolf howl pack lone animal' },
      { char: '🐗', name: 'boar wild pig tusks' },
      { char: '🐴', name: 'horse face pony stallion' },
      { char: '🦄', name: 'unicorn magic fantasy rainbow rare startup' },
      { char: '🐝', name: 'honeybee bee honey buzz pollen' },
      { char: '🐛', name: 'bug caterpillar insect debug software glitch' },
      { char: '🦋', name: 'butterfly beauty wings metamorph' },
      { char: '🐌', name: 'snail slow slime shell' },
      { char: '🐞', name: 'lady beetle ladybug insect luck' },
      { char: '🐜', name: 'ant insect worker small team' },
      { char: '🪲', name: 'beetle bug insect' },
      { char: '🪳', name: 'cockroach bug roach resilient' },
      { char: '🕷️', name: 'spider arachnid web crawler spooky' },
      { char: '🕸️', name: 'spider web internet net code trap' },
      { char: '🦂', name: 'scorpion sting desert venom' },
      { char: '🐢', name: 'turtle slow steady reptile shell' },
      { char: '🐍', name: 'snake python reptile code serpent' },
      { char: '🦎', name: 'lizard gecko reptile green' },
      { char: '🦖', name: 't rex dinosaur jurassic extinct powerful' },
      { char: '🦕', name: 'sauropod dinosaur dino brontosaurus' },
      { char: '🐙', name: 'octopus eight arms marine sea ocean tentacles' },
      { char: '🦑', name: 'squid ocean sea kraken calamari' },
      { char: '🦐', name: 'shrimp prawn seafood' },
      { char: '🦞', name: 'lobster seafood red ocean' },
      { char: '🦀', name: 'crab crustacean ocean beach rust language' },
      { char: '🐡', name: 'blowfish puffer sea ocean spikes' },
      { char: '🐠', name: 'tropical fish aquarium nemo' },
      { char: '🐟', name: 'fish seafood swimming ocean river' },
      { char: '🐬', name: 'dolphin smart marine ocean jump' },
      { char: '🐳', name: 'spouting whale ocean huge massive giant' },
      { char: '🐋', name: 'whale ocean sea massive blue whale' },
      { char: '🦈', name: 'shark ocean predator jaws fin' },
      { char: '🦭', name: 'seal ocean arctic cute' },
      { char: '🐊', name: 'crocodile alligator swamp reptile reptile' },
      { char: '🐅', name: 'tiger wild feline striped predator' },
      { char: '🐆', name: 'leopard cheetah fast spots speed' },
      { char: '🦓', name: 'zebra stripes safari animal' },
      { char: '🦍', name: 'gorilla silverback strong ape primate' },
      { char: '🦧', name: 'orangutan ape jungle orange' },
      { char: '🦣', name: 'mammoth prehistoric extinct ice age' },
      { char: '🐘', name: 'elephant trunk huge memory big animal' },
      { char: '🦛', name: 'hippopotamus hippo water heavy' },
      { char: '🦏', name: 'rhinoceros rhino horn heavy savanna' },
      { char: '🐪', name: 'camel desert hump dry' },
      { char: '🐫', name: 'two hump camel bactrian desert' },
      { char: '🦒', name: 'giraffe tall neck spots safari' },
      { char: '🦘', name: 'kangaroo australia jump hop pouch' },
      { char: '🦬', name: 'bison buffalo plains wild' },
      { char: '🐃', name: 'water buffalo ox heavy horn' },
      { char: '🐂', name: 'ox bull strong livestock' },
      { char: '🐄', name: 'cow cattle milk farm dairy' },
      { char: '🐎', name: 'horse race speed gallop' },
      { char: '🐖', name: 'pig farm pork sow swine' },
      { char: '🐏', name: 'ram male sheep horn aries' },
      { char: '🐑', name: 'ewe sheep wool fluffy fleece' },
      { char: '🦙', name: 'llama alpaca wool andes' },
      { char: '🐐', name: 'goat greatest of all time horns' },
      { char: '🦌', name: 'deer buck stag forest antlers' },
      { char: '🐕', name: 'dog pet puppy loyal hound' },
      { char: '🐩', name: 'poodle dog fancy pet curly' },
      { char: '🦮', name: 'guide dog blind assistance service' },
      { char: '🐕‍🦺', name: 'service dog assistance vest working' },
      { char: '🐈', name: 'cat feline pet meow domestic' },
      { char: '🐈‍⬛', name: 'black cat spooky superstition halloween' },
      { char: '🐓', name: 'rooster cock crow morning sunrise' },
      { char: '🦃', name: 'turkey thanksgiving gobble bird' },
      { char: '🦤', name: 'dodo extinct mauritius bird' },
      { char: '🦚', name: 'peacock feathers beauty colourful show' },
      { char: '🦜', name: 'parrot pirate talk mimic tropical' },
      { char: '🦢', name: 'swan grace lake white bird' },
      { char: '🦩', name: 'flamingo pink tropical stand one leg' },
      { char: '🕊️', name: 'dove peace olive branch white bird' },
      { char: '🐇', name: 'rabbit bunny fast burrow' },
      { char: '🦝', name: 'raccoon trash panda mask bandit' },
      { char: '🦨', name: 'skunk stink smell stripe odor' },
      { char: '🦡', name: 'badger fearless animal dig' },
      { char: '🦫', name: 'beaver dam builder wood engineering' },
      { char: '🦦', name: 'otter river cute water playful' },
      { char: '🦥', name: 'sloth slow lazy sleep chill' },
      { char: '🐁', name: 'mouse rodent small squeak' },
      { char: '🐀', name: 'rat rodent cheese street' },
      { char: '🐿️', name: 'chipmunk squirrel nuts acorn forest' },
      { char: '🦔', name: 'hedgehog spikes quill cute sonic' },
      { char: '🐾', name: 'paw prints animal tracks dog cat footprint' },
      { char: '🐉', name: 'dragon mythical beast fantasy fire breathing' },
      { char: '🐲', name: 'dragon face oriental green mythical' },
      { char: '🌵', name: 'cactus plant desert sharp spines' },
      { char: '🎄', name: 'christmas tree holiday celebration winter' },
      { char: '🌲', name: 'evergreen tree pine forest nature' },
      { char: '🌳', name: 'deciduous tree nature forest oxygen green' },
      { char: '🌴', name: 'palm tree tropical beach vacation summer' },
      { char: '🌱', name: 'seedling sprout plant grow start new green' },
      { char: '🌿', name: 'herb plant green leaf organic cooking' },
      { char: '☘️', name: 'shamrock clover ireland saint patrick 3 leaf' },
      { char: '🍀', name: 'four leaf clover luck lucky fortune fortune green' },
      { char: '🎍', name: 'pine decoration bamboo japanese festival' },
      { char: '🪴', name: 'potted plant houseplant indoor green decor' },
      { char: '🍃', name: 'leaf fluttering in wind breeze nature autumn' },
      { char: '🍂', name: 'fallen leaf autumn fall season orange leaves' },
      { char: '🍁', name: 'maple leaf autumn fall canada orange' },
      { char: '🍄', name: 'mushroom fungus toadstool red mario' },
      { char: '🌾', name: 'sheaf of rice grain agriculture crop harvest' },
      { char: '💐', name: 'bouquet flowers gift celebration congratulations love' },
      { char: '🌷', name: 'tulip spring flower pink blossom' },
      { char: '🌹', name: 'rose red flower love romance valentine' },
      { char: '🥀', name: 'wilted flower dying dead rose sad' },
      { char: '🌺', name: 'hibiscus tropical flower red exotic hawaii' },
      { char: '🌸', name: 'cherry blossom sakura pink spring japan flower' },
      { char: '🌼', name: 'blossom yellow flower spring daisy' },
      { char: '🌻', name: 'sunflower yellow sunny summer bright seeds' },
      { char: '🌞', name: 'sun with face sunshine summer morning happy' },
      { char: '🌝', name: 'full moon face smiling night space' },
      { char: '🌛', name: 'first quarter moon face night sleep' },
      { char: '🌜', name: 'last quarter moon face night dream' },
      { char: '🌚', name: 'new moon face creepy dark night smirk' },
      { char: '🌕', name: 'full moon round glowing bright night' },
      { char: '🌖', name: 'waning gibbous moon space cycle' },
      { char: '🌗', name: 'last quarter moon half space phase' },
      { char: '🌘', name: 'waning crescent moon thin sliver' },
      { char: '🌑', name: 'new moon black dark eclipse' },
      { char: '🌒', name: 'waxing crescent moon phase' },
      { char: '🌓', name: 'first quarter moon half' },
      { char: '🌔', name: 'waxing gibbous moon' },
      { char: '🌙', name: 'crescent moon night sleep dreams ramadan' },
      { char: '🌎', name: 'globe showing americas earth planet world global' },
      { char: '🌍', name: 'globe showing europe africa earth world planet' },
      { char: '🌏', name: 'globe showing asia australia earth world international' },
      { char: '🪐', name: 'ringed planet saturn space astronomy cosmic' },
      { char: '💫', name: 'dizzy star shooting star magic sparkle shine' },
      { char: '⭐', name: 'star gold favorite rating review bright shining' },
      { char: '🌟', name: 'glowing star sparkle bright shine achievement top' },
      { char: '✨', name: 'sparkles sparkle magic shine glitter AI star clean new' },
      { char: '⚡', name: 'high voltage lightning bolt power fast energy flash electrify' },
      { char: '☄️', name: 'comet space meteor shooting star cosmic' },
      { char: '💥', name: 'collision explosion boom bang impact blast crash' },
      { char: '🔥', name: 'fire flame lit hot trend burning passion awesome' },
      { char: '🌪️', name: 'tornado cyclone twister storm weather wind' },
      { char: '🌈', name: 'rainbow colors colorful pride nature sky optimism' },
      { char: '☀️', name: 'sun sunny weather clear day warm bright summer' },
      { char: '🌤️', name: 'sun behind small cloud partly sunny weather' },
      { char: '⛅', name: 'sun behind cloud cloudy overcast weather' },
      { char: '🌥️', name: 'sun behind large cloud gloomy' },
      { char: '☁️', name: 'cloud cloudy weather overcast server aws sky' },
      { char: '🌦️', name: 'sun behind rain cloud sun shower drizzle' },
      { char: '🌧️', name: 'cloud with rain rainy wet storm weather shower' },
      { char: '⛈️', name: 'cloud with lightning and rain thunderstorm storm' },
      { char: '🌩️', name: 'cloud with lightning thunder electric' },
      { char: '🌨️', name: 'cloud with snow winter cold blizzard' },
      { char: '❄️', name: 'snowflake snow winter cold ice freeze chill crisp' },
      { char: '☃️', name: 'snowman snow winter holiday festive frosty' },
      { char: '⛄', name: 'snowman without snow frosty winter' },
      { char: '🌬️', name: 'wind face blowing breeze storm' },
      { char: '💨', name: 'dashing away fast speed run sprint smoke puff zoom' },
      { char: '💧', name: 'droplet water drop sweat teardrop aqua rain' },
      { char: '💦', name: 'sweat droplets water splash workout hard work' },
      { char: '🫧', name: 'bubbles soap clean floating water' },
      { char: '🌊', name: 'water wave tsunami ocean sea surf tide surge' }
    ]
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { char: '🍏', name: 'green apple fruit healthy fresh' },
      { char: '🍎', name: 'red apple fruit education teacher tech' },
      { char: '🍐', name: 'pear fruit healthy sweet' },
      { char: '🍊', name: 'tangerine orange citrus vitamin c fruit' },
      { char: '🍋', name: 'lemon citrus sour yellow fruit' },
      { char: '🍌', name: 'banana fruit monkey yellow potassium' },
      { char: '🍉', name: 'watermelon melon summer sweet fruit slice' },
      { char: '🍇', name: 'grapes wine fruit purple bunch' },
      { char: '🍓', name: 'strawberry berry fruit red sweet summer' },
      { char: '🫐', name: 'blueberries berry fruit blue antioxidant' },
      { char: '🍈', name: 'melon cantaloupe honeydew sweet fruit' },
      { char: '🍒', name: 'cherries cherry fruit red sweet twin' },
      { char: '🍑', name: 'peach fruit juicy sweet bottom' },
      { char: '🥭', name: 'mango tropical fruit sweet king of fruits' },
      { char: '🍍', name: 'pineapple tropical fruit hawaii sweet exotic' },
      { char: '🥥', name: 'coconut tropical palm water nut' },
      { char: '🥝', name: 'kiwi fruit fuzzy green new zealand' },
      { char: '🍅', name: 'tomato red salad vegetable fruit salsa' },
      { char: '🥑', name: 'avocado guacamole toast healthy fat green' },
      { char: '🍆', name: 'eggplant aubergine vegetable purple' },
      { char: '🥔', name: 'potato spud chips french fries vegetable' },
      { char: '🥕', name: 'carrot orange vegetable rabbit eyesight' },
      { char: '🌽', name: 'ear of corn maize popcorn grain yellow' },
      { char: '🌶️', name: 'hot pepper chili spicy red hot fiery' },
      { char: '🫑', name: 'bell pepper capsicum green salad' },
      { char: '🥒', name: 'cucumber pickle salad vegetable cool' },
      { char: '🥬', name: 'leafy green salad lettuce spinach kale healthy' },
      { char: '🥦', name: 'broccoli tree vegetable healthy green' },
      { char: '🧄', name: 'garlic clove seasoning cooking flavor vamp' },
      { char: '🧅', name: 'onion vegetable cry cooking layers' },
      { char: '🥜', name: 'peanuts groundnut snack butter allergy' },
      { char: '🫘', name: 'beans legume protein chili coffee' },
      { char: '🌰', name: 'chestnut nut acorn autumn winter' },
      { char: '🍞', name: 'bread loaf toast bakery carbs slice' },
      { char: '🥐', name: 'croissant french bakery pastry butter breakfast' },
      { char: '🥖', name: 'baguette bread french bakery loaf' },
      { char: '🫓', name: 'flatbread pita roti naan chapati taco' },
      { char: '🥨', name: 'pretzel salted snack bavarian knot' },
      { char: '🥯', name: 'bagel breakfast cream cheese bakery bread' },
      { char: '🥞', name: 'pancakes breakfast syrup butter stack flapjacks' },
      { char: '🧇', name: 'waffle breakfast syrup belgian butter' },
      { char: '🧀', name: 'cheese wedge dairy cheddar swiss gouda' },
      { char: '🍖', name: 'meat on bone roast anime food carnivore' },
      { char: '🍗', name: 'poultry leg chicken drumstick fried turkey' },
      { char: '🥩', name: 'cut of meat steak beef raw barbecue bbq' },
      { char: '🥓', name: 'bacon pork breakfast crispy strip meat' },
      { char: '🍔', name: 'hamburger burger fast food cheese bun beef patty' },
      { char: '🍟', name: 'french fries chips mcdonalds fast food potato' },
      { char: '🍕', name: 'pizza slice cheese pepperoni italian fast food pie' },
      { char: '🌭', name: 'hot dog frankfurter sausage mustard fast food' },
      { char: '🥪', name: 'sandwich lunch sub bread deli club' },
      { char: '🌮', name: 'taco mexican fast food shell beef tortilla' },
      { char: '🌯', name: 'burrito mexican wrap wrap chipotle' },
      { char: '🫔', name: 'tamale mexican traditional corn masa' },
      { char: '🥙', name: 'stuffed flatbread kebab gyros shawarma falafel' },
      { char: '🧆', name: 'falafel middle eastern chickpea fried ball' },
      { char: '🥚', name: 'egg breakfast shell raw protein oval' },
      { char: '🍳', name: 'cooking fried egg sunny side up pan breakfast' },
      { char: '🥘', name: 'shallow pan of food paella curry casserole dinner' },
      { char: '🍲', name: 'pot of food stew soup hot bowl broth' },
      { char: '🫕', name: 'fondue cheese dip swiss melted chocolate pot' },
      { char: '🥣', name: 'bowl with spoon soup cereal oatmeal breakfast' },
      { char: '🥗', name: 'green salad healthy vegetarian veggies diet bowl' },
      { char: '🍿', name: 'popcorn movie cinema snack cinema butter' },
      { char: '🧈', name: 'butter dairy spread cook grease yellow block' },
      { char: '🧂', name: 'salt shaker seasoning sodium flavor spice' },
      { char: '🥫', name: 'canned food tin can soup beans storage' },
      { char: '🍱', name: 'bento box japanese lunch meal rice fish' },
      { char: '🍘', name: 'rice cracker senbei japanese snack' },
      { char: '🍙', name: 'rice ball onigiri nori japanese seaweed' },
      { char: '🍚', name: 'cooked rice white rice bowl grain staple' },
      { char: '🍛', name: 'curry rice indian japanese spicy sauce stew' },
      { char: '🍜', name: 'steaming bowl ramen noodles soup broth chopsticks' },
      { char: '🍝', name: 'spaghetti pasta noodles italian tomato sauce' },
      { char: '🍠', name: 'roasted sweet potato yam street food winter' },
      { char: '🍢', name: 'oden japanese skewer street food soup' },
      { char: '🍣', name: 'sushi japanese fish nigiri raw seafood rolls' },
      { char: '🍤', name: 'fried shrimp tempura seafood japanese prawn' },
      { char: '🍥', name: 'fish cake with swirl narutomaki ramen topper' },
      { char: '🥮', name: 'mooncake mid autumn festival pastry chinese' },
      { char: '🍡', name: 'dango japanese dessert skewer sweet mochi' },
      { char: '🥟', name: 'dumpling gyoza dim sum potsticker pierogi' },
      { char: '🥠', name: 'fortune cookie chinese restaurant prediction future' },
      { char: '🥡', name: 'takeout box chinese food container noodle carton' },
      { char: '🍦', name: 'soft ice cream soft serve cone vanilla summer' },
      { char: '🍧', name: 'shaved ice dessert syrup kakigori snow cone' },
      { char: '🍨', name: 'ice cream sundae bowl scoop dessert sweet' },
      { char: '🍩', name: 'doughnut donut sweet pastry glaze sprinkles' },
      { char: '🍪', name: 'cookie chocolate chip sweet biscuit snack internet' },
      { char: '🎂', name: 'birthday cake celebration candles party dessert' },
      { char: '🍰', name: 'shortcake cake slice strawberry dessert sweet' },
      { char: '🧁', name: 'cupcake icing frosting bakery sweet muffin' },
      { char: '🥧', name: 'pie bakery dessert fruit crust apple pie' },
      { char: '🍫', name: 'chocolate bar sweet cocoa candy treat cocoa' },
      { char: '🍬', name: 'candy sweet sugar wrapper confection' },
      { char: '🍭', name: 'lollipop candy sweet spiral sucker sugar' },
      { char: '🍮', name: 'custard flan pudding caramel dessert sweet' },
      { char: '🍯', name: 'honey pot sweet bee bear breakfast syrup' },
      { char: '🍼', name: 'baby bottle milk infant drink feed' },
      { char: '🥛', name: 'glass of milk dairy drink calcium white glass' },
      { char: '☕', name: 'hot beverage coffee tea espresso morning cafe coder caffeine' },
      { char: '🫖', name: 'teapot tea kettle brew porcelain hot drink' },
      { char: '🍵', name: 'teacup without handle green tea matcha japanese herbal' },
      { char: '🍶', name: 'sake japanese rice wine bottle cup ceramic' },
      { char: '🍾', name: 'bottle with popping cork champagne celebrate party sparkling' },
      { char: '🍷', name: 'wine glass red wine alcohol drink vineyard dinner' },
      { char: '🍸', name: 'cocktail glass martini olive alcohol lounge' },
      { char: '🍹', name: 'tropical drink cocktail beach vacation umbrella fruity' },
      { char: '🍺', name: 'beer mug alcohol ale lager pub bar cheers' },
      { char: '🍻', name: 'clinking beer mugs cheers toast pub party friends celebrate' },
      { char: '🥂', name: 'clinking glasses cheers champagne toast celebrate anniversary' },
      { char: '🥃', name: 'tumbler glass whiskey scotch bourbon liquor on rocks' },
      { char: '🥤', name: 'cup with straw soda drink fast food beverage plastic' },
      { char: '🧋', name: 'bubble tea boba tapioca milk tea drink sweet pearls' },
      { char: '🧃', name: 'beverage box juice box straw kids drink fruit' },
      { char: '🧉', name: 'mate drink yerba south america herbal infusion gourd' },
      { char: '🧊', name: 'ice cube cold chill freezer freeze solid cool' }
    ]
  },
  {
    id: 'activity',
    name: 'Activities & Sports',
    icon: '⚽',
    emojis: [
      { char: '⚽', name: 'soccer ball football sports FIFA match' },
      { char: '🏀', name: 'basketball sports hoop NBA slam dunk ball' },
      { char: '🏈', name: 'american football NFL super bowl sports ball' },
      { char: '⚾', name: 'baseball MLB sports bat glove ball' },
      { char: '🥎', name: 'softball sports yellow ball pitch' },
      { char: '🎾', name: 'tennis racket court grand slam ball' },
      { char: '🏐', name: 'volleyball beach sports spike court' },
      { char: '🏉', name: 'rugby football sports scrum ball' },
      { char: '🥏', name: 'flying disc frisbee ultimate disc golf park' },
      { char: '🎱', name: 'pool 8 ball billiards cue game magic 8 ball' },
      { char: '🪀', name: 'yo-yo toy string trick spin' },
      { char: '🏓', name: 'ping pong table tennis paddle ball game' },
      { char: '🏸', name: 'badminton shuttlecock racket court sports' },
      { char: '🏒', name: 'ice hockey stick puck NHL winter ice' },
      { char: '🏑', name: 'field hockey stick ball sports grass' },
      { char: '🥍', name: 'lacrosse stick ball mesh sports' },
      { char: '🏏', name: 'cricket game bat ball wicket test match IPL world cup' },
      { char: '🪃', name: 'boomerang australia throw return wood' },
      { char: '🥅', name: 'goal net sports soccer hockey score target' },
      { char: '⛳', name: 'flag in hole golf green course putt stroke' },
      { char: '🪁', name: 'kite fly wind festival spring toy sky' },
      { char: '🏹', name: 'bow and arrow archery target robin hood bullseye' },
      { char: '🎣', name: 'fishing pole fish hook lake catch reel' },
      { char: '🤿', name: 'diving mask snorkel underwater ocean swim' },
      { char: '🥊', name: 'boxing glove punch ring fight bout workout' },
      { char: '🥋', name: 'martial arts uniform karate judo taekwondo gi black belt' },
      { char: '🎽', name: 'running shirt marathon track sash athlete' },
      { char: '🛹', name: 'skateboard skate deck ollie wheels street' },
      { char: '🛼', name: 'roller skate quad skates rink derby retro' },
      { char: '🛷', name: 'sled sledge winter snow downhill sleigh' },
      { char: '⛸️', name: 'ice skate figure skating rink winter blade' },
      { char: '🥌', name: 'curling stone winter sports ice broom' },
      { char: '🎿', name: 'skis ski snow winter mountain slope alpine' },
      { char: '⛷️', name: 'skier ski slope snow winter athlete' },
      { char: '🏂', name: 'snowboarder snowboard winter mountain halfpipe' },
      { char: '🪂', name: 'parachute skydiving extreme sport jump drop' },
      { char: '🏋️', name: 'person lifting weights gym bodybuilding fitness deadlift crossfit' },
      { char: '🤼', name: 'people wrestling wrestle fight match sports' },
      { char: '🤸', name: 'person cartwheeling gymnastics acrobat flip' },
      { char: '⛹️', name: 'person bouncing ball basketball athlete dribble' },
      { char: '🤺', name: 'person fencing sword duel foil epee' },
      { char: '🤾', name: 'person playing handball sports indoor' },
      { char: '🧗', name: 'person climbing rock bouldering mountaineering peak' },
      { char: '🧘', name: 'person in lotus position yoga meditate zen peace mindfulness' },
      { char: '🏇', name: 'horse racing jockey derby race equestrian' },
      { char: '🚴', name: 'person biking bicycle cyclist ride tour de france' },
      { char: '🚵', name: 'person mountain biking mountain bike trail offroad' },
      { char: '🏆', name: 'trophy win prize champion award 1st place gold contest winner' },
      { char: '🥇', name: '1st place medal gold medal champion first winner' },
      { char: '🥈', name: '2nd place medal silver medal runner up second' },
      { char: '🥉', name: '3rd place medal bronze medal third place' },
      { char: '🏅', name: 'sports medal military honor award achievement' },
      { char: '🎖️', name: 'military medal ribbon decoration honor bravery' },
      { char: '🏵️', name: 'rosette ribbon award plant flower' },
      { char: '🎗️', name: 'reminder ribbon awareness support cause' },
      { char: '🎫', name: 'ticket admission cinema event entry raffle' },
      { char: '🎟️', name: 'admission tickets movie cinema theater festival' },
      { char: '🎪', name: 'circus tent carnival big top fair performance' },
      { char: '🤹', name: 'person juggling circus skill multitasking perform' },
      { char: '🎭', name: 'performing arts drama theater masks acting comedy tragedy' },
      { char: '🎨', name: 'artist palette paint art painting design color UI UX' },
      { char: '🎬', name: 'clapper board film movie cinema action director take' },
      { char: '🎤', name: 'microphone mic singing karaoke podcast voice speech' },
      { char: '🎧', name: 'headphone headphones music audio podcast sound listen beats' },
      { char: '🎼', name: 'musical score music sheet notes symphony song' },
      { char: '🎹', name: 'musical keyboard piano keys synthesizer notes' },
      { char: '🥁', name: 'drum drumsticks beat rhythm percussion music' },
      { char: '🎷', name: 'saxophone jazz brass instrument music' },
      { char: '🎺', name: 'trumpet brass horn fanfare jazz fanfare' },
      { char: '🎸', name: 'guitar electric acoustic rock music strings strum' },
      { char: '🪕', name: 'banjo bluegrass folk instrument strings' },
      { char: '🎻', name: 'violin classical orchestra fiddle strings bow' },
      { char: '🎲', name: 'game die dice roll gambling board game random luck' },
      { char: '♟️', name: 'chess pawn strategy game board opening move checkmate' },
      { char: '🎯', name: 'direct hit target bullseye accuracy goal metric milestone darts' },
      { char: '🎳', name: 'bowling ball pins strike spare alley game' },
      { char: '🎮', name: 'video game controller joystick gaming play playstation xbox' },
      { char: '👾', name: 'alien monster retro arcade space invader 8bit' },
      { char: '🎰', name: 'slot machine 777 casino jackpot gambling 7' }
    ]
  },
  {
    id: 'travel',
    name: 'Travel & Places',
    icon: '✈️',
    emojis: [
      { char: '🚗', name: 'automobile car vehicle transport drive road' },
      { char: '🚕', name: 'taxi cab yellow ride uber lyft passenger' },
      { char: '🚙', name: 'sport utility vehicle suv car jeep offroad' },
      { char: '🚌', name: 'bus public transport transit commuter school' },
      { char: '🚎', name: 'trolleybus electric public transport' },
      { char: '🏎️', name: 'racing car formula 1 f1 motorsport fast race' },
      { char: '🚓', name: 'police car law emergency siren cop' },
      { char: '🚑', name: 'ambulance medical emergency hospital red cross siren' },
      { char: '🚒', name: 'fire engine fire truck firefighter rescue siren' },
      { char: '🚐', name: 'minibus van passenger cargo camper' },
      { char: '🛻', name: 'pickup truck cargo utility flatbed load' },
      { char: '🚚', name: 'delivery truck freight cargo shipment transport' },
      { char: '🚛', name: 'articulated lorry semi truck big rig cargo haul' },
      { char: '🚜', name: 'tractor agriculture farm field heavy equipment' },
      { char: '🦯', name: 'white cane accessibility blind visually impaired' },
      { char: '🦽', name: 'manual wheelchair accessibility disability' },
      { char: '🦼', name: 'motorized wheelchair electric accessibility' },
      { char: '🛴', name: 'kick scooter electric city commuter micro mobility' },
      { char: '🚲', name: 'bicycle bike cycling commuter exercise transport' },
      { char: '🛵', name: 'motor scooter vespa moped delivery courier' },
      { char: '🏍️', name: 'motorcycle motorbike biker speed harley ride' },
      { char: '🛺', name: 'auto rickshaw tuk tuk taxi transport' },
      { char: '🚨', name: 'police car light emergency red alert siren warning emergency alarm' },
      { char: '🚔', name: 'oncoming police car cop law enforcement patrol' },
      { char: '🚍', name: 'oncoming bus transit public transport' },
      { char: '🚘', name: 'oncoming automobile car traffic' },
      { char: '🚖', name: 'oncoming taxi cab yellow transport' },
      { char: '🚡', name: 'aerial tramway cable car ski resort mountain' },
      { char: '🚠', name: 'mountain cableway gondola mountain ski view' },
      { char: '🚟', name: 'suspension railway monorail train transit' },
      { char: '🚃', name: 'railway car electric train tram carriage' },
      { char: '🚋', name: 'tram car streetcar trolley city transit' },
      { char: '🚞', name: 'mountain railway cog train scenic slope' },
      { char: '🚝', name: 'monorail single rail transit theme park airport' },
      { char: '🚄', name: 'high speed train bullet shinkansen fast rail express' },
      { char: '🚅', name: 'bullet train shinkansen fast speed japan railway' },
      { char: '🚈', name: 'light rail metro commuter train' },
      { char: '🚂', name: 'locomotive steam train vintage engine antique' },
      { char: '🚆', name: 'train railway commute travel tracks' },
      { char: '🚇', name: 'metro subway underground transit train tube' },
      { char: '🚊', name: 'tram streetcar public transport' },
      { char: '🚉', name: 'station railway train platform transit stop' },
      { char: '✈️', name: 'airplane flight flight trip travel aviation fly airport' },
      { char: '🛫', name: 'airplane departure takeoff fly flight launch' },
      { char: '🛬', name: 'airplane arrival landing airport touchdown' },
      { char: '🛩️', name: 'small airplane cessna private prop aviation' },
      { char: '💺', name: 'seat chair passenger airline ticket airplane' },
      { char: '🛰️', name: 'satellite space orbit comms gps tech telescope' },
      { char: '🚀', name: 'rocket space ship launch takeoff deploy speed growth startup scale moon' },
      { char: '🛸', name: 'flying saucer ufo alien extraterrestrial sci fi' },
      { char: '🚁', name: 'helicopter chopper flight rotor rescue aviation' },
      { char: '🛶', name: 'canoe kayak paddle river lake boat row' },
      { char: '⛵', name: 'sailboat yacht sailing wind boat marine' },
      { char: '🚤', name: 'speedboat motorboat water fast power marine' },
      { char: '🛳️', name: 'passenger ship cruise liner vessel travel ocean' },
      { char: '⛴️', name: 'ferry boat passenger transport island car ferry' },
      { char: '🚢', name: 'ship boat cargo freight container tanker ocean' },
      { char: '⚓', name: 'anchor nautical ship marine dock sea port security' },
      { char: '🛟', name: 'ring buoy life preserver safety rescue life ring' },
      { char: '⛽', name: 'fuel pump gas petrol station refuel diesel charge' },
      { char: '🚧', name: 'construction barrier under construction WIP progress danger warning' },
      { char: '🚦', name: 'vertical traffic light signal stop go road' },
      { char: '🚥', name: 'horizontal traffic light signal road intersection' },
      { char: '🗺️', name: 'world map geography atlas travel navigate location' },
      { char: '🗿', name: 'moai easter island stone statue rock ancient' },
      { char: '🗽', name: 'statue of liberty new york freedom monument usa' },
      { char: '🗼', name: 'tokyo tower japan landmark eiffel tall' },
      { char: '🏰', name: 'castle fortress fairytale medieval royalty disney kingdom' },
      { char: '🏯', name: 'japanese castle fortress pagoda ancient' },
      { char: '🏟️', name: 'stadium arena match crowd concert sports venue' },
      { char: '🎡', name: 'ferris wheel carnival amusement park fair ride' },
      { char: '🎢', name: 'roller coaster theme park ride thrills excitement' },
      { char: '🎠', name: 'carousel horse merry go round amusement fair' },
      { char: '⛲', name: 'fountain water park architecture monument public' },
      { char: '⛱️', name: 'umbrella on ground beach sun vacation summer resort' },
      { char: '🏖️', name: 'beach with umbrella ocean sea sand vacation holiday' },
      { char: '🏝️', name: 'desert island tropical palm beach isolated retreat' },
      { char: '🏜️', name: 'desert sand dunes hot dry barren sahara' },
      { char: '🌋', name: 'volcano eruption lava magma smoke mountain explosion' },
      { char: '⛰️', name: 'mountain peak nature alps climb high' },
      { char: '🏔️', name: 'snow capped mountain everest summit cold peak winter' },
      { char: '🏕️', name: 'camping tent campfire outdoor nature retreat woods' },
      { char: '⛺', name: 'tent camping outdoor festival shelter' },
      { char: '🛖', name: 'hut shack thatch simple home rural' },
      { char: '🏠', name: 'house home building residence domestic stay' },
      { char: '🏡', name: 'house with garden home yard suburb tree real estate' },
      { char: '🏘️', name: 'houses neighborhood suburb community village' },
      { char: '🏚️', name: 'derelict house abandoned broken spooky ruin' },
      { char: '🏗️', name: 'building construction crane site framework erect architecture' },
      { char: '🏢', name: 'office building company headquarters corporate skyscraper work workplace' },
      { char: '🏣', name: 'japanese post office mail delivery service' },
      { char: '🏤', name: 'post office mail postal courier building' },
      { char: '🏥', name: 'hospital healthcare medicine doctor clinic emergency nurse' },
      { char: '🏦', name: 'bank finance money loans vault investment ATM' },
      { char: '🏨', name: 'hotel lodge accommodation hospitality room resort' },
      { char: '🏩', name: 'love hotel motel romance heart' },
      { char: '🏪', name: 'convenience store 24 7 grocery shop mini mart' },
      { char: '🏫', name: 'school education college university academy classroom study campus' },
      { char: '🏬', name: 'department store mall retail shopping market store' },
      { char: '🏭', name: 'factory industry manufacturing smoke assembly warehouse' },
      { char: '🏛️', name: 'classical building bank government courthouse museum parthenon column' },
      { char: '⛪', name: 'church religion christian chapel wedding worship' },
      { char: '🕌', name: 'mosque islam muslim minaret dome ramadan' },
      { char: '🛕', name: 'hindu temple temple worship mandir sacred' },
      { char: '🕍', name: 'synagogue jewish religion worship temple star of david' },
      { char: '🕋', name: 'kaaba mecca islam pilgrimage hajj holy' },
      { char: '🗾', name: 'map of japan country island nippon' },
      { char: '🎑', name: 'moon viewing ceremony harvest autumn japan' },
      { char: '🌅', name: 'sunrise morning dawn sun horizon ocean daybreak' },
      { char: '🌄', name: 'sunrise over mountains morning sun peak dawn' },
      { char: '🌠', name: 'shooting star meteor wish night sky magic' },
      { char: '🎇', name: 'sparkler fireworks celebration festive party light' },
      { char: '🎆', name: 'fireworks celebration new year new years eve party explosive festival' },
      { char: '🌇', name: 'sunset dusk evening twilight golden hour cityscape' },
      { char: '🌆', name: 'cityscape at dusk sunset skyline buildings twilight' },
      { char: '🏙️', name: 'cityscape city skyline skyscrapers metropolis urban' },
      { char: '🌃', name: 'night with stars night cityscape stars skyline dark' },
      { char: '🌌', name: 'milky way galaxy space stars universe cosmic astronomy' },
      { char: '🌉', name: 'bridge at night golden gate suspension night bridge lights' },
      { char: '🌁', name: 'foggy bridge fog san francisco golden gate mist' }
    ]
  },
  {
    id: 'objects',
    name: 'Objects & Tech',
    icon: '💡',
    emojis: [
      { char: '💻', name: 'laptop computer PC dev macbook coder tech notebook coding hardware' },
      { char: '🖥️', name: 'desktop computer monitor iMac screen workstation display dev' },
      { char: '🖨️', name: 'printer document print paper hardware office' },
      { char: '⌨️', name: 'keyboard typing mechanical keys input coder dev QWERTY' },
      { char: '🖱️', name: 'computer mouse click pointer optical hardware' },
      { char: '💽', name: 'minidisc computer disk optical storage data' },
      { char: '💾', name: 'floppy disk save diskette 3.5 storage retro backup vintage' },
      { char: '💿', name: 'optical disk CD disc DVD music storage data' },
      { char: '📀', name: 'DVD video movie disc storage media' },
      { char: '🧮', name: 'abacus calculate math count ancient ledger arithmetic' },
      { char: '🎥', name: 'movie camera film cinema video recording shoot Hollywood' },
      { char: '🎞️', name: 'film frames movie reel cinema strip camera roll' },
      { char: '📽️', name: 'film projector presentation cinema screen retro movie' },
      { char: '📺', name: 'television TV monitor screen broadcast display stream' },
      { char: '📷', name: 'camera photo picture snapshot DSLR shoot flash' },
      { char: '📸', name: 'camera with flash snapshot photo paparazzi capture' },
      { char: '📹', name: 'video camera camcorder recording VHS broadcast live' },
      { char: '📼', name: 'videocassette tape VHS retro tape 90s media' },
      { char: '🔍', name: 'magnifying glass tilted left search look zoom inspect find query' },
      { char: '🔎', name: 'magnifying glass tilted right search find look inspect examine' },
      { char: '🕯️', name: 'candle flame wax light illumination birthday mood' },
      { char: '💡', name: 'light bulb idea inspiration smart innovation electricity solution tip Eureka' },
      { char: '🔦', name: 'flashlight torch light beam dark search find' },
      { char: '🏮', name: 'red paper lantern festival celebration izakaya japan light' },
      { char: '🪔', name: 'diya lamp oil diwali festival hindu clay light' },
      { char: '📔', name: 'notebook with decorative cover journal diary study binder' },
      { char: '📕', name: 'closed book red reading literature textbook manual' },
      { char: '📖', name: 'open book reading study literature textbook education learn doc' },
      { char: '📗', name: 'green book reading study library education green' },
      { char: '📘', name: 'blue book study manual textbook guide documentation' },
      { char: '📙', name: 'orange book study reading textbook binder' },
      { char: '📚', name: 'books stack reading study college education school campus library homework' },
      { char: '📓', name: 'notebook composition book lined journal notes homework' },
      { char: '📒', name: 'ledger yellow spiral notepad accounting notes records' },
      { char: '📃', name: 'page with curl document paper invoice receipt letter form' },
      { char: '📜', name: 'scroll parchment ancient declaration charter document degree diploma' },
      { char: '📄', name: 'page facing up document paper text blank file report contract' },
      { char: '📰', name: 'newspaper press media daily news journalism headline print' },
      { char: '🗞️', name: 'rolled up newspaper delivery media news print journal' },
      { char: '📑', name: 'bookmark tabs document tags index flags organized notes' },
      { char: '🔖', name: 'bookmark favorite reading save tag mark ribbon' },
      { char: '🏷️', name: 'label tag price item metadata category badge brand' },
      { char: '💰', name: 'money bag dollar cash wealth rich currency treasure funds' },
      { char: '🪙', name: 'coin crypto token gold currency money payment' },
      { char: '💴', name: 'yen banknote currency japan money cash payment' },
      { char: '💵', name: 'dollar banknote cash currency USD money greenback bills' },
      { char: '💶', name: 'euro banknote EU currency money cash payment' },
      { char: '💷', name: 'pound banknote UK sterling currency money cash' },
      { char: '💸', name: 'money with wings flying away spend expenses cash loss waste' },
      { char: '💳', name: 'credit card payment debit visa mastercard banking transaction purchase' },
      { char: '🧾', name: 'receipt bill expense transaction checkout invoice proof' },
      { char: '✉️', name: 'envelope email mail message letter postal inbox contact' },
      { char: '📧', name: 'e-mail email letter message communication online' },
      { char: '📨', name: 'incoming envelope receive mail email notification inbox' },
      { char: '📩', name: 'envelope with arrow send mail email outbox message' },
      { char: '📤', name: 'outbox tray sent mail upload send dispatch file' },
      { char: '📥', name: 'inbox tray receive mail inbox download file deposit' },
      { char: '📦', name: 'package parcel box delivery shipment courier amazon order' },
      { char: '📫', name: 'closed mailbox with raised flag mail notification post letter' },
      { char: '📪', name: 'closed mailbox with lowered flag post office letter' },
      { char: '📬', name: 'open mailbox with raised flag mail delivered post' },
      { char: '📭', name: 'open mailbox with lowered flag empty mail inbox' },
      { char: '📮', name: 'postbox mailbox letter collection red royal mail' },
      { char: '🗳️', name: 'ballot box with ballot vote democracy election choice poll' },
      { char: '✏️', name: 'pencil write draw draft edit sketch lead graphite' },
      { char: '✒️', name: 'black nib fountain pen calligraphy write signature ink' },
      { char: '🖋️', name: 'fountain pen writing signature autograph ink elegance' },
      { char: '🖊️', name: 'pen ballpoint write notes ink signing document' },
      { char: '🖌️', name: 'paintbrush paint artist stroke art canvas render' },
      { char: '🖍️', name: 'crayon wax color drawing kids art sketch' },
      { char: '📝', name: 'memo notepad note writing task list checklist to-do plan text memo' },
      { char: '💼', name: 'briefcase business portfolio work professional career job briefcase' },
      { char: '📁', name: 'file folder storage directory archive documents system data' },
      { char: '📂', name: 'open file folder directory explore browse storage open' },
      { char: '🗂️', name: 'card index dividers organized sorting filing tabs' },
      { char: '📅', name: 'calendar date schedule event month deadline appointment agenda' },
      { char: '📆', name: 'tear off calendar date daily schedule event reminder plan' },
      { char: '🗒️', name: 'spiral notepad notes writing scratchpad scribble memo' },
      { char: '🗓️', name: 'spiral calendar date event timeline milestone schedule' },
      { char: '📇', name: 'card index rolodex contacts directory organizer network' },
      { char: '📈', name: 'chart increasing upward trend growth stats success stock profit metrics' },
      { char: '📉', name: 'chart decreasing downward trend loss stats drop stock decline recession' },
      { char: '📊', name: 'bar chart analytics dashboard stats report data metrics comparison' },
      { char: '📋', name: 'clipboard tasks list survey audit inspection review form checklist' },
      { char: '📌', name: 'pushpin pin map location stick note reminder mark pinned' },
      { char: '📍', name: 'round pushpin map location GPS pin marker point of interest' },
      { char: '📎', name: 'paperclip attach attachment file link connect join document' },
      { char: '🖇️', name: 'linked paperclips attach documents connect network relationship' },
      { char: '📏', name: 'straight ruler measure distance centimeters inches draw layout' },
      { char: '📐', name: 'triangular ruler geometry architecture measurement draft angle' },
      { char: '✂️', name: 'scissors cut snip shear trim tool craft tailor' },
      { char: '🗃️', name: 'card file box archive storage index records database' },
      { char: '🗄️', name: 'file cabinet office storage archive metal records paperwork' },
      { char: '🗑️', name: 'wastebasket trash garbage recycle delete bin remove discard' },
      { char: '🔒', name: 'locked security privacy pad lock safe secure password encryption auth' },
      { char: '🔓', name: 'unlocked open access insecurity exposed release permission access' },
      { char: '🔏', name: 'locked with pen digital signature privacy auth cipher privacy sign' },
      { char: '🔐', name: 'locked with key secure security auth secret key code cipher' },
      { char: '🔑', name: 'key password unlock security access authentication credentials pass' },
      { char: '🗝️', name: 'old key antique vintage secret skeleton key access mystery' },
      { char: '🔨', name: 'hammer tool build hit nails construction hardware DIY fix' },
      { char: '🪓', name: 'axe woodchop tool lumberjack chop sharp' },
      { char: '⛏️', name: 'pickaxe mining dig rock underground quarry goldcraft' },
      { char: '⚒️', name: 'hammer and pick tools mining construction building craft forge' },
      { char: '🛠️', name: 'hammer and wrench tools fix settings repair configure custom build develop' },
      { char: '🗡️', name: 'dagger blade knife sword sharp medieval weapon attack' },
      { char: '⚔️', name: 'crossed swords battle fight duel conflict combat war' },
      { char: '💣', name: 'bomb explosive blast impact TNT destruction weapon crisis' },
      { char: '🪃', name: 'boomerang weapon return throw wood circle' },
      { char: '🏹', name: 'bow and arrow archery target weapon aim hunt' },
      { char: '🛡️', name: 'shield defense protect security armor safeguard firewalls antivirus' },
      { char: '🪚', name: 'carpentry saw cut wood lumber tool construction' },
      { char: '🔧', name: 'wrench spanner tool mechanic fix repair adjust configure setting' },
      { char: '🪛', name: 'screwdriver tool mechanic fix screw tighten assemble' },
      { char: '🔩', name: 'nut and bolt hardware screw fasten metal construction fix' },
      { char: '⚙️', name: 'gear settings engine machinery mechanics options config preferences process' },
      { char: '🗜️', name: 'clamp vice compress press hardware woodworking hold' },
      { char: '⚖️', name: 'balance scale justice law legal fairness equality weigh rights' },
      { char: '🦯', name: 'probing cane accessibility blind navigation guide' },
      { char: '🔗', name: 'link hyperlink url web connect bond join relation URL' },
      { char: '⛓️', name: 'chains bond bondage restriction locked metal link connected' },
      { char: '🪝', name: 'hook pirate fishing hang catch grab anchor' },
      { char: '🧰', name: 'toolbox kit repair mechanic maintenance equipment supplies' },
      { char: '🧲', name: 'magnet attraction magnetic force pull physics red horseshoe' },
      { char: '🪜', name: 'ladder climb steps elevation progress career height reach' },
      { char: '⚗️', name: 'alembic chemistry alchemy distillation science lab potion' },
      { char: '🧪', name: 'test tube chemistry science experiment laboratory research test clinical' },
      { char: '🧫', name: 'petri dish biology culture bacteria laboratory scientific sample' },
      { char: '🧬', name: 'dna genetics biology hereditary genome helix code double helix' },
      { char: '🔬', name: 'microscope science laboratory research biology zoom analysis optics' },
      { char: '🔭', name: 'telescope astronomy star gaze cosmic space optics explore discovery' },
      { char: '📡', name: 'satellite antenna communication dish broadcast signal radar wireless' },
      { char: '💉', name: 'syringe needle medicine medical vaccine doctor blood injection' },
      { char: '🩸', name: 'drop of blood medical donation vampire blood donor transfusion' },
      { char: '💊', name: 'pill capsule medicine healthcare pharmacy tablet drug remedy' },
      { char: '🩹', name: 'adhesive bandage bandaid injury first aid cure fix heal' },
      { char: '🩺', name: 'stethoscope medical doctor nurse heartbeat exam clinic health' },
      { char: '🚪', name: 'door entrance exit threshold open close gate access' },
      { char: '🛗', name: 'elevator lift up down floor accessibility transit' },
      { char: '🪞', name: 'mirror reflection glass look vanity look glass' },
      { char: '🪟', name: 'window glass frame view breeze sunshine transparency' },
      { char: '🛏️', name: 'bed sleep furniture rest bedroom hotel mattress' },
      { char: '🛋️', name: 'couch and lamp sofa living room furniture relax lounge home' },
      { char: '🪑', name: 'chair seat furniture sit desk dining stool' },
      { char: '🚽', name: 'toilet restroom bathroom porcelain washroom loo' },
      { char: '🪠', name: 'plunger toilet drain unclog plumbing tool suction' },
      { char: '🚿', name: 'shower bathroom wash clean water bath hygiene' },
      { char: '🛁', name: 'bathtub bath relax bathroom wash soak bubbles' },
      { char: '🪤', name: 'mouse trap trap bait catch snap' },
      { char: '🪒', name: 'razor shave blade sharp grooming hygiene' },
      { char: '🧴', name: 'lotion bottle moisturizer cream shampoo soap dispenser' },
      { char: '🧷', name: 'safety pin attach diaper secure metal fastener' },
      { char: '🧹', name: 'broom sweep clean chore dust floor witch' },
      { char: '🧺', name: 'basket laundry wicker woven picnic storage' },
      { char: '🧻', name: 'roll of paper toilet paper tissue wipe paper towel hygiene' },
      { char: '🪣', name: 'bucket pail water mop wash construction carry' },
      { char: '🧼', name: 'soap wash lather clean hygiene bubbles bath bar' },
      { char: '🪥', name: 'toothbrush dental hygiene teeth smile brush paste' },
      { char: '🧽', name: 'sponge clean wash soak scrub porous dish' },
      { char: '🧯', name: 'fire extinguisher safety emergency fire rescue put out' },
      { char: '🛒', name: 'shopping cart supermarket ecommerce buy retail store purchase checkout' }
    ]
  },
  {
    id: 'symbols',
    name: 'Symbols & Status',
    icon: '🔣',
    emojis: [
      { char: '❤️', name: 'red heart love passion valentine romance favorite like' },
      { char: '🧡', name: 'orange heart love care friendship warmth' },
      { char: '💛', name: 'yellow heart love friendship sunshine golden happiness' },
      { char: '💚', name: 'green heart love nature organic jealousy environmental' },
      { char: '💙', name: 'blue heart love loyalty peace trust calm ocean' },
      { char: '💜', name: 'purple heart love luxury royalty compassion deep magic' },
      { char: '🤎', name: 'brown heart love earth cocoa solidarity coffee' },
      { char: '🖤', name: 'black heart dark love gothic heavy deep' },
      { char: '🤍', name: 'white heart pure love clean peace innocent' },
      { char: '💔', name: 'broken heart sadness breakup heartbroken grief hurt' },
      { char: '❤️‍🔥', name: 'heart on fire passion burning love intense desire energy' },
      { char: '❤️‍🩹', name: 'mending heart healing recovery better love again' },
      { char: '❣️', name: 'heart exclamation love excited punctuation point' },
      { char: '💕', name: 'two hearts floating love affection pink hearts' },
      { char: '💞', name: 'revolving hearts love orbit romance mutual' },
      { char: '💓', name: 'beating heart love pulse heartbeat emotion viva' },
      { char: '💗', name: 'growing heart love expansion warm affection' },
      { char: '💖', name: 'sparkling heart love sparkle shine dazzle cute' },
      { char: '💘', name: 'heart with arrow cupid struck love romance valentine' },
      { char: '💝', name: 'heart with ribbon gift love present valentine wrapped' },
      { char: '💟', name: 'heart decoration purple square badge lovely' },
      { char: '☮️', name: 'peace symbol pacifism harmony nonviolence antiwar' },
      { char: '✝️', name: 'latin cross christianity religion faith jesus' },
      { char: '☪️', name: 'star and crescent islam muslim religion faith' },
      { char: '🕉️', name: 'om symbol hinduism sacred sound mantra spirituality' },
      { char: '☸️', name: 'wheel of dharma buddhism dharma chakra religion eightfold' },
      { char: '✡️', name: 'star of david judaism religion jewish flag' },
      { char: '🔯', name: 'six pointed star hexagram fortune symbol star' },
      { char: '🕎', name: 'menorah candelabra hanukkah jewish religion holiday' },
      { char: '☯️', name: 'yin yang balance harmony dual taoism opposite' },
      { char: '☦️', name: 'orthodox cross eastern christianity religion faith' },
      { char: '🛐', name: 'place of worship religion pray spirituality kneel' },
      { char: '⛎', name: 'ophiuchus zodiac constellation astrology serpent bearer' },
      { char: '♈', name: 'aries zodiac ram astrology horoscopes fire' },
      { char: '♉', name: 'taurus zodiac bull astrology horoscope earth' },
      { char: '♊', name: 'gemini zodiac twins astrology horoscope air' },
      { char: '♋', name: 'cancer zodiac crab astrology horoscope water' },
      { char: '♌', name: 'leo zodiac lion astrology horoscope fire sun' },
      { char: '♍', name: 'virgo zodiac maiden astrology horoscope earth' },
      { char: '♎', name: 'libra zodiac scales balance astrology air' },
      { char: '♏', name: 'scorpio zodiac scorpion astrology water' },
      { char: '♐', name: 'sagittarius zodiac archer astrology fire' },
      { char: '♑', name: 'capricorn zodiac sea goat astrology earth' },
      { char: '♒', name: 'aquarius zodiac water bearer astrology air' },
      { char: '♓', name: 'pisces zodiac fishes astrology water' },
      { char: '🆔', name: 'ID button identification identifier credentials identity proof' },
      { char: '⚛️', name: 'atom symbol physics science nuclear quantum reaction' },
      { char: '🉑', name: 'japanese acceptable button pass agree ok' },
      { char: '☢️', name: 'radioactive hazard nuclear danger radiation toxic' },
      { char: '☣️', name: 'biohazard biological hazard danger virus quarantine' },
      { char: '📴', name: 'mobile phone off silence quiet silent mode mute' },
      { char: '📳', name: 'vibration mode mobile phone ring silent vibrate' },
      { char: '🈶', name: 'japanese not free of charge fee charge cost' },
      { char: '🈚', name: 'japanese free of charge no cost complimentary zero' },
      { char: '🈸', name: 'japanese application button apply request submit form' },
      { char: '🈺', name: 'japanese open for business open available operating' },
      { char: '🈷️', name: 'japanese monthly amount month bill period' },
      { char: '✴️', name: 'eight pointed star star sparkle orange' },
      { char: '🆚', name: 'VS button versus competition duel matchup faceoff' },
      { char: '💮', name: 'white flower stamp good job well done award praise' },
      { char: '🉐', name: 'japanese bargain button profit gain deal discount' },
      { char: '㊙️', name: 'japanese secret button confidential classified private' },
      { char: '㊗️', name: 'japanese congratulations button celebrate praise blessed' },
      { char: '🈴', name: 'japanese passing grade button pass passed exam test' },
      { char: '🈵', name: 'japanese full capacity button full no vacancy occupied' },
      { char: '🈹', name: 'japanese discount button sale bargain off' },
      { char: '🈲', name: 'japanese prohibited button banned restricted no forbidden' },
      { char: '🅰️', name: 'A button blood type letter alphabet A' },
      { char: '🅱️', name: 'B button blood type letter alphabet B' },
      { char: '🆎', name: 'AB button blood type letters' },
      { char: '🆑', name: 'CL button clear wipe reset remove' },
      { char: '🅾️', name: 'O button blood type letter zero round' },
      { char: '🆘', name: 'SOS button emergency help rescue distress signal danger' },
      { char: '❌', name: 'cross mark cancel error wrong false reject decline no X failure delete' },
      { char: '⭕', name: 'hollow red circle correct ring right answer yes OK' },
      { char: '🛑', name: 'stop sign halt traffic red octagon danger cease pause' },
      { char: '⛔', name: 'no entry road sign forbidden access denied restricted' },
      { char: '📛', name: 'name badge tag ID identification visitor guest' },
      { char: '🚫', name: 'prohibited no sign forbidden disallowed ban stop' },
      { char: '💯', name: 'hundred points score perfect 100 100% exam test absolute true' },
      { char: '💢', name: 'anger symbol manga veins mad angry frustration popping' },
      { char: '♨️', name: 'hot springs onsen steam bath relaxation thermal' },
      { char: '🚷', name: 'no pedestrians prohibited walking banned' },
      { char: '🚯', name: 'no littering keep clean trash forbidden' },
      { char: '🚳', name: 'no bicycles bikes banned prohibited' },
      { char: '🚱', name: 'non potable water do not drink toxic' },
      { char: '🔞', name: 'no one under eighteen 18+ adult mature restricted' },
      { char: '📵', name: 'no mobile phones forbidden silence device' },
      { char: '🚭', name: 'no smoking forbidden cigarette smoke ban' },
      { char: '❗', name: 'red exclamation mark alert warning notice urgent priority attention bang' },
      { char: '❕', name: 'white exclamation mark alert notice info' },
      { char: '❓', name: 'red question mark ask query question help confusion' },
      { char: '❔', name: 'white question mark inquiry doubt query' },
      { char: '‼️', name: 'double exclamation mark high alert urgent attention priority danger' },
      { char: '⁉️', name: 'exclamation question mark interrobang surprise shock disbelief ask' },
      { char: '🔅', name: 'dim button low brightness dark light reduce' },
      { char: '🔆', name: 'bright button high brightness sun glare illuminate' },
      { char: '〽️', name: 'part alternation mark music singing traditional' },
      { char: '⚠️', name: 'warning alert caution risk error attention hazard notice' },
      { char: '🚸', name: 'children crossing school zone caution safety kids' },
      { char: '🔱', name: 'trident emblem poseidon sea weapon pitchfork power' },
      { char: '⚜️', name: 'fleur de lis royal emblem lily coat of arms french' },
      { char: '🔰', name: 'japanese symbol for beginner novice rookie newbie greenhorn new start' },
      { char: '♻️', name: 'recycling symbol recycle eco green reusable circular' },
      { char: '✅', name: 'check mark button check done completed approved success correct pass verify' },
      { char: '🈯', name: 'japanese reserved button booking booked reserved slot' },
      { char: '💹', name: 'chart increasing with yen market currency profit rise' },
      { char: '❇️', name: 'sparkle star green flourish shine' },
      { char: '✳️', name: 'eight spoked asterisk star wildcard math' },
      { char: '❎', name: 'cross mark button cancel wrong reject fail' },
      { char: '🌐', name: 'globe with meridians internet web network worldwide online connect' },
      { char: '💠', name: 'diamond with a dot cute blossom kawaii gem' },
      { char: 'Ⓜ️', name: 'circled M metro subway transit mark' },
      { char: '🌀', name: 'cyclone spiral hurricane storm vortex twist spin' },
      { char: '💤', name: 'zzz sleep tired snoring dreaming nap' },
      { char: '🏧', name: 'ATM sign automated teller machine cash bank withdrawal' },
      { char: '🚾', name: 'water closet bathroom toilet WC washroom' },
      { char: '♿', name: 'wheelchair symbol accessibility disability handicap accessible' },
      { char: '🅿️', name: 'P button parking car lot space permit' },
      { char: '🛗', name: 'elevator lift accessibility floor' },
      { char: '🈳', name: 'japanese vacancy button available open free slot' },
      { char: '🈂️', name: 'japanese service button service free assistance' },
      { char: '🛂', name: 'passport control immigration border travel airport customs' },
      { char: '🛃', name: 'customs airport inspection baggage border border check' },
      { char: '🛄', name: 'baggage claim luggage carousel airport arrivals collection' },
      { char: '🛅', name: 'left luggage locker baggage storage airport station' },
      { char: '🚹', name: 'mens room restroom bathroom male gentlemen' },
      { char: '🚺', name: 'womens room restroom bathroom female ladies' },
      { char: '🚼', name: 'baby symbol infant nursery changing room diaper' },
      { char: '⚧️', name: 'transgender symbol gender pride identity' },
      { char: '🚻', name: 'restroom WC bathroom all gender public toilet' },
      { char: '🚩', name: 'triangular flag milestone red flag marker goal priority checkpoint' },
      { char: '🏁', name: 'chequered flag finish line racing winner completed done champion victory' },
      { char: '🏳️', name: 'white flag surrender peace truce yield stop' },
      { char: '🏴', name: 'black flag pirate rebel darkness banner' },
      { char: '🏴‍☠️', name: 'pirate flag skull crossbones jolly roger buccaneer' },
      { char: '📢', name: 'loudspeaker announcement broadcast team room megaphone notify' },
      { char: '📣', name: 'megaphone cheer shout cheering loud broadcast alert broadcast' },
      { char: '🔔', name: 'bell notification alert alarm reminder ring chime sound' },
      { char: '🔕', name: 'bell with slash mute silence no notifications quiet do not disturb' },
      { char: '💬', name: 'speech balloon chat comment message text discussion speech bubble' },
      { char: '💭', name: 'thought balloon think daydream wonder idea bubble' },
      { char: '🗯️', name: 'right anger bubble mad shout exclamation comics' },
      { char: '🗨️', name: 'left speech balloon dialogue chat speech' },
      { char: '🗯️', name: 'anger bubble explosion shout scream' },
      { char: '🟢', name: 'green circle active online available pass live ready status' },
      { char: '🟡', name: 'yellow circle away idle warning pause pending status' },
      { char: '🔴', name: 'red circle busy offline error stop danger record status' },
      { char: '🟠', name: 'orange circle in progress busy working status' },
      { char: '🟣', name: 'purple circle focus lead VIP special status' },
      { char: '🔵', name: 'blue circle info neutral verified status' },
      { char: '⚪', name: 'white circle neutral clear inactive status' },
      { char: '⚫', name: 'black circle off dark stealth status' },
      { char: '⬛', name: 'black large square block' },
      { char: '⬜', name: 'white large square block' },
      { char: '🔶', name: 'large orange diamond gem luxury badge' },
      { char: '🔷', name: 'large blue diamond verified badge tech mark' },
      { char: '🔸', name: 'small orange diamond' },
      { char: '🔹', name: 'small blue diamond' },
      { char: '🔺', name: 'red triangle pointed up increase up gain' },
      { char: '🔻', name: 'red triangle pointed down decrease down drop' },
      { char: '💠', name: 'diamond with dot kawaii blossom' },
      { char: '🔘', name: 'radio button selection chosen option target' },
      { char: '🔳', name: 'white square button UI toggle checkbox' },
      { char: '🔲', name: 'black square button UI control' },
      { char: '🔄', name: 'counterclockwise arrows button reload refresh sync update loop restart' },
      { char: '🔃', name: 'clockwise vertical arrows refresh reload update loop' },
      { char: '🔀', name: 'shuffle tracks button random mix playlist' },
      { char: '🔁', name: 'repeat button loop replay infinite rerun' },
      { char: '🔂', name: 'repeat single button repeat once track 1 loop' },
      { char: '▶️', name: 'play button start video audio stream begin' },
      { char: '⏩', name: 'fast forward button speed skip rush ahead' },
      { char: '⏭️', name: 'next track button skip next step' },
      { char: '⏯️', name: 'play or pause button toggle playback media' },
      { char: '◀️', name: 'reverse button back previous' },
      { char: '⏪', name: 'fast reverse button rewind back history' },
      { char: '⏮️', name: 'last track button previous step jump back' },
      { char: '🔼', name: 'upwards button arrow up high' },
      { char: '⏫', name: 'fast up button increase elevate boost' },
      { char: '🔽', name: 'downwards button arrow down low' },
      { char: '⏬', name: 'fast down button drop lower decrease' },
      { char: '⏸️', name: 'pause button hold stop wait temporary' },
      { char: '⏹️', name: 'stop button halt terminate end finish' },
      { char: '⏺️', name: 'record button recording live capture audio video' },
      { char: '⏏️', name: 'eject button remove disk extract safely release' }
    ]
  }
];
